command = "sway"
outputMode = "all"
scale = 1

[background]
red = 0
green = 0
blue = 0
opacity = 0.9

[headline]
red = 1.0
green = 1.0
blue = 1.0
opacity = 1.0

[prompt]
red = 1.0
green = 1.0
blue = 1.0
opacity = 1.0

[promptErr]
red = 1.0
green = 1.0
blue = 1.0
opacity = 1.0

[border]
red = 1.0
green = 1.0
blue = 1.0
opacity = 1.0
