(deftheme ryanakca
  "Created 2013-03-01.")

(custom-theme-set-faces
 'ryanakca
 '(default ((t (:inherit nil :stipple nil :background "#080808" :foreground "#eeeeee" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 83 :width normal :foundry "unknown" :family "Inconsolata"))))
 '(cursor ((t (:background "green" :foreground "black"))))
 '(fixed-pitch ((t (:family "courier"))))
 '(variable-pitch ((t (:family "helv"))))
 '(escape-glyph ((t (:foreground "purple2"))))
 '(minibuffer-prompt ((t (:foreground "chartreuse" :weight bold))))
 '(highlight ((t (:underline t :foreground "#ffffff" :background "DodgerBlue4"))))
 '(region ((t (:foreground "#f6f3e8" :background "#103050"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((t (:background "#a40000"))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#DC45DC" :inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#DC45DC" :slant oblique))))
 '(font-lock-constant-face ((t (:foreground "orchid" :weight bold))))
 '(font-lock-doc-face ((t (:slant oblique :foreground "moccasin" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "deep sky blue" :weight bold :height 1.1))))
 '(font-lock-keyword-face ((t (:foreground "yellow" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:slant italic :foreground "gold" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "burlywood"))))
 '(font-lock-type-face ((t (:weight bold :foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((t (:weight bold :foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:inherit error :foreground "red" :weight bold))))
 '(button ((t (:weight bold :underline t :box (:line-width 2 :color "grey" :style released-button) :foreground "#f6f3e8" :background "#333333" :inherit (link)))))
 '(link ((t (:foreground "#afffff" :underline t))))
 '(link-visited ((t (:underline t :foreground "#afd7ff" :inherit link))))
 '(fringe ((t (:foreground "Wheat" :background "black"))))
 '(header-line ((t (:height 0.9 :box (:line-width -1 :color "grey20" :style released-button) :inverse-video t :foreground "#e7f6da" :background "#303030" :inherit (mode-line)))))
 '(tooltip ((t (:family "helv" :foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:family "DejaVu Sans" :height 0.9 :box (:line-width 1 :color nil :style released-button) :foreground "black" :background "gray75"))))
 '(mode-line-buffer-id ((t (:height 0.9 :weight bold :underline "red" :overline "red" :foreground "blue4"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(mode-line-inactive ((t (:height 0.9 :weight light :box (:line-width 1 :color "gray40" :style nil) :foreground "black" :background "gray40" :inherit (mode-line)))))
 '(isearch ((t (:background "#d7afff" :foreground "#5f0000"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "white" :background "cadetblue"))))
 '(match ((t (:background "DeepPink4"))))
 '(next-error ((t (:background "blue3" :inherit (region)))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2" :inherit (isearch))))))

(provide-theme 'ryanakca)
