directory: /media/wd/music_clean
library: /media/wd/music_clean/beetsmusic.blb
plugins: mbsync duplicates fetchart mbcollection badfiles

import:
    incremental: true
    quiet_fallback: skip
    log: /media/wd/music_clean/import_log
    move: true
    write: true
    autotag: true

paths:
    default: $format/$albumartist/$album/$track $title
    singleton: $format/Singletons/$artist - $title
    comp: $format/comp/$album/$track $title

musicbrainz:
    user: MBUSER
    pass: MBPASS
    auto: yes

match:
    preferred:
        countries: ['CA', 'US']
        media: ['CD']
