# Automatically migrated from legacy .beetsconfig.

directory: /media/wd/music_clean
library: /media/wd/music_clean/beetsmusic.blb
path_format: $format/$artist/$album/$track $title
plugins: mbsync duplicates fetchart

import:
    incremental: true
    quiet_fallback: skip
    log: /media/wd/music_clean/import_log
    move: true

paths:
    default: $format/$albumartist/$album/$track $title
    singleton: $format/Singletons/$artist - $title
    comp: $format/comp/$album/$track $title
