#!/bin/sh

apt-upgrade() {
    sudo apt-get update && sudo apt-get dist-upgrade
}

1920s() {
    mpv -playlist 'http://kara.fast-serv.com:8398/listen.pls'
}
dismuke() {
    mpv -playlist 'https://early1900s.org/radiodismuke/radiodismuke.pls'
}
wzum() {
    mpv 'http://pubmusic.streamguys1.com/wzum-aac'
}
wesa() {
    # WESA JazzWorks
    mpv 'https://ais-sa3.cdnstream1.com/2558_128.aac'
}
wyep() {
    mpv 'https://ais-sa3.cdnstream1.com/2557_128.aac'
}

alias mplayer-fb='mplayer -vo fbdev'
alias links2-fb='links2 -driver fb'

alias itp='reportbug -M -B debian --email rak@debian.org --paranoid -K $GPGKEY wnpp'
alias gibuild='gbp buildpackage --git-builder="sbuild -sAd u"'
alias gibuildi='gbp buildpackage --git-ignore-new --git-builder="sbuild -sAd u"'
alias dquilt="quilt --quiltrc=~/.quiltrc-dpkg"

alias vi='vim'

alias sm='tmux attach -t mail || tmux -f ${HOME}/.tmux-mail.conf attach -t mail'
alias sshfw='ssh -oForwardAgent=yes'

# escape ${XDG_STATE_HOME} to use the value when invoked rather than
# the value at definition time
alias llocate="locate -d \${XDG_STATE_HOME}/plocate/home.db"

# Alias/custom commands
#
# Many of these options don's exist on BSD rm/cp/mkdir/ln/etc.
#
# Some are just in case - for 'rm', 'cp' and 'mv' - ask about overwriting or
# deleting files.
# Furthermore, be verbose about what each command is performing to be present of
# what is occuring every time.
if [ "$(uname)" = "Linux" ]; then
    alias cp="cp -iv"
    alias mkdir="mkdir -v"
    alias mv="mv -iv"
    alias ln="ln -v"
    # Only delete files on the current file system to avoid removing recursively
    # from bind mounts.
    alias rm="rm -iv --one-file-system"

    alias grep="grep --colour=auto"

    alias chown="chown -v"
    alias chmod="chmod -v"
    alias ls="ls --classify --color=always" # Add all colours and
                                            # have fancy symbols for files, etc.
elif [ "$(uname )" = "OpenBSD" ] && [ -x /usr/local/bin/colorls ]; then
    alias ls="colorls -G"
fi

# vim: set ft=sh:
